In [1]:
import numpy as np

##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [8]:
array = np.array([0,1.2,2,3.0], dtype="int")
print(array.ndim)
print(array.size)
array

1
4


array([0, 1, 2, 3])

##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [17]:
arr2=np.array([[1,2,6,7], [4,3,9,5]])
print(f"Boyutu = {arr2.ndim}")
print(f"Eleman sayısı = {arr2.size}")
print(f"Satır sütün bilgisi {np.shape(arr2)}")
print("--------")
arr3=np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])
print(f"Boyutu = {arr3.ndim}")
print(f"Eleman sayısı = {arr3.size}")
print(f"Satır sütün bilgisi {np.shape(arr3)}")

Boyutu = 2
Eleman sayısı = 8
Satır sütün bilgisi (2, 4)
--------
Boyutu = 3
Eleman sayısı = 12
Satır sütün bilgisi (2, 2, 3)


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [18]:
arr2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [19]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
arr2[0,1]

2

In [20]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
arr2[0,3]

7

In [21]:
arr3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [22]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
arr3[1,1,2]

9

In [23]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
arr3[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [26]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
arr2[0,1:3]

array([2, 6])

In [28]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
arr2[1,1:]

array([3, 9, 5])

In [29]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
arr3[0,1,:]

array([21,  8, 11])

In [30]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
arr3[1,0,1:]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [33]:
sıfırarray= np.zeros((5,3),dtype="int")
birarray = np.ones((5,3),dtype="int")

In [34]:
satir = np.concatenate([sıfırarray, birarray], axis=0)
sutun = np.concatenate([sıfırarray, birarray], axis=1)
print("Satır bazında birleştirme:\n", satir)
print("Sütun bazında birleştirme:\n", sutun)

Satır bazında birleştirme:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Sütun bazında birleştirme:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
